### ISSUE TITLE
If the Yubikey has a password the workflow does not work

### ISSUE THREAD

**Issue by leobartowski** [robertoriv/alfred-yubikey-otp#10]

**Comment by nihuyah** [comment]
You are right, you must specify the password and save it on device first. Open up the terminal and type `ykman oath remember-password`. It saves the password locally just the way Yubico Authenticator does. 

Just keep in mind it is not perfect, as the stored password may lead to 2FA compromise if someone gets in possession of the yubikey and your laptop simultaneously.

**Comment by leobartowski** [comment]
Ok, thanks a lot. It worked perfectly.
